title: Walk
default_lang: en
author:
  name: 'Walk Homestay'
  email: walkhomestay@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Provide homestay ''s information throughout the country'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
